<a href="https://colab.research.google.com/github/ApurvaMayank-iitb/24D0894_IE643_NIFTI/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import matplotlib as plt
import numpy as np

In [2]:
print(torch.__version__)

2.5.1+cu121


In [3]:
print(torch.__version__)

2.5.1+cu121


In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [5]:
tensor = torch.tensor([7,8,9])

In [6]:
tensor

tensor([7, 8, 9])

In [7]:
tensor.shape

torch.Size([3])

In [8]:
tensor.ndim

1

In [9]:
matrix = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])

In [10]:
matrix.ndim

3

In [11]:
matrix.shape

torch.Size([1, 3, 3])

In [12]:
matrix[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [13]:
matrix[0][1][1]

tensor(4)

In [14]:
matrix[0][2]

tensor([6, 7, 8])

In [15]:
matrix[0][0][2]

tensor(3)

In [16]:
matrix.shape

torch.Size([1, 3, 3])

In [17]:
### Random Tensors

###Random Tensors

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

Start with random numbers >> look at data >> update random numbers>> look at data>> update random numbers

In [18]:
## Create a random tensor of size (3,4)
random_tensor = torch.rand(3,3,4)

In [19]:
random_tensor

tensor([[[0.4551, 0.4253, 0.9568, 0.2530],
         [0.0617, 0.3767, 0.5102, 0.8059],
         [0.0848, 0.2443, 0.5260, 0.6041]],

        [[0.5383, 0.3188, 0.5207, 0.4076],
         [0.3745, 0.8087, 0.6054, 0.2433],
         [0.1496, 0.0773, 0.8734, 0.2570]],

        [[0.8207, 0.4952, 0.6957, 0.4451],
         [0.1867, 0.1848, 0.3536, 0.6357],
         [0.7913, 0.5659, 0.8121, 0.0608]]])

In [20]:
random_tensor.ndim

3

In [21]:
random_tensor.shape

torch.Size([3, 3, 4])

In [22]:
## Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels (R,G,B)

In [23]:
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width , colour channels (R,G,B)

In [24]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [25]:
random_image_size_tensor

tensor([[[6.8912e-01, 9.4818e-01, 2.0430e-01],
         [4.8924e-01, 1.5877e-01, 5.0378e-01],
         [6.3083e-01, 2.1557e-01, 2.7991e-01],
         ...,
         [3.1612e-01, 3.5792e-01, 3.5865e-01],
         [2.6142e-01, 7.6917e-01, 2.9940e-01],
         [3.4250e-01, 1.2336e-01, 6.2834e-02]],

        [[6.6254e-01, 9.5497e-01, 6.3550e-01],
         [1.1917e-01, 9.1919e-01, 4.5613e-01],
         [9.9389e-01, 1.5034e-01, 9.6082e-01],
         ...,
         [2.7307e-02, 4.9652e-01, 8.7594e-01],
         [1.8200e-01, 9.4257e-01, 3.9532e-01],
         [6.5244e-01, 5.9013e-01, 8.0321e-01]],

        [[4.2178e-01, 1.8791e-01, 6.1637e-01],
         [3.2892e-01, 4.5297e-01, 1.0859e-01],
         [2.1845e-01, 9.7724e-01, 4.4998e-01],
         ...,
         [8.6154e-01, 9.4371e-01, 7.0687e-01],
         [7.3732e-01, 6.9676e-01, 5.8761e-01],
         [5.5563e-01, 6.2881e-01, 5.2834e-01]],

        ...,

        [[3.4615e-01, 4.9743e-01, 4.9806e-04],
         [9.0491e-01, 7.2121e-01, 5.8429e-01]

In [26]:
### Zeros and Ones

In [27]:
zero = torch.zeros(size=(3,4))

In [28]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

Range and Tensors like other tensor

In [32]:
# Use torch.range()
torch.range(0,10)

<ipython-input-32-a70e3231c961>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
one_to_ten = torch.arange(1,11)

In [34]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
one_to_thousand = torch.arange(start=1, end= 1000, step = 7)
one_to_thousand

tensor([  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,  92,
         99, 106, 113, 120, 127, 134, 141, 148, 155, 162, 169, 176, 183, 190,
        197, 204, 211, 218, 225, 232, 239, 246, 253, 260, 267, 274, 281, 288,
        295, 302, 309, 316, 323, 330, 337, 344, 351, 358, 365, 372, 379, 386,
        393, 400, 407, 414, 421, 428, 435, 442, 449, 456, 463, 470, 477, 484,
        491, 498, 505, 512, 519, 526, 533, 540, 547, 554, 561, 568, 575, 582,
        589, 596, 603, 610, 617, 624, 631, 638, 645, 652, 659, 666, 673, 680,
        687, 694, 701, 708, 715, 722, 729, 736, 743, 750, 757, 764, 771, 778,
        785, 792, 799, 806, 813, 820, 827, 834, 841, 848, 855, 862, 869, 876,
        883, 890, 897, 904, 911, 918, 925, 932, 939, 946, 953, 960, 967, 974,
        981, 988, 995])

In [36]:
# creating tensors like
ten_zeros = torch.zeros_like(input = one_to_thousand)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
ten_zeros.size

<function Tensor.size>

## Dealing with tensor datatypes

In [38]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None)

In [39]:
float_32_tensor

tensor([3., 6., 9.])

In [40]:
float_32_tensor.dtype

torch.float32

In [41]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [42]:
float_16_tensor.dtype

torch.float16

In [43]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what datatype is the tensor (e.g float32 or float16)
                               device= None, # What device is your tensor on
                               requires_grad = False) # Wheter or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

### Note : Tensor datatype is one of the 3 big errors you"ll run into with PyTorch & deep learning :

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [44]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [45]:
int_32_tensor = torch.tensor([3,6,9],dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [46]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors

1. Tensor not right datatype - do get datatype from a tensor , can use "tensor.dtype"
2. Tensor not right shape - to get shape from a tensor , can use "tensor.shape"
3. Tensor not right device - to get the device from a tensor , can use "tensor.device"

In [47]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6385, 0.4338, 0.7162, 0.9541],
        [0.8179, 0.9341, 0.8916, 0.2088],
        [0.5787, 0.8471, 0.6244, 0.5146]])

In [48]:
## Find out details about some_tensor

In [49]:
print(some_tensor)
print(f"Datatype of tensor = {some_tensor.dtype}")
print(f"Shape of tensor = {some_tensor.shape}")
print(f"Device of the tensor = {some_tensor.device}")

tensor([[0.6385, 0.4338, 0.7162, 0.9541],
        [0.8179, 0.9341, 0.8916, 0.2088],
        [0.5787, 0.8471, 0.6244, 0.5146]])
Datatype of tensor = torch.float32
Shape of tensor = torch.Size([3, 4])
Device of the tensor = cpu


## Manipulating Tensors ( Tensor operations)
Tensor operations include addition ,subtraction , multiplication(element wise) , division and matrix multiplication

In [50]:
## Create a tensor
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [51]:
tensor + 100

tensor([101, 102, 103])

In [52]:
# Multiply tensor by 10
tensor  = tensor*10

In [53]:
tensor

tensor([10, 20, 30])

In [54]:
tensor - 10

tensor([ 0, 10, 20])

In [55]:
## Try out Pytorch inbuilt functions
torch.mul(tensor,10)

tensor([100, 200, 300])

In [56]:
torch.add(tensor,20)

tensor([30, 40, 50])

## Matrix Multiplication
There are two main ways of performing mutiplication in neural networks and deep learning :

1. Element wise multiplication
2. Matrix multiplication(dot product)

More information on multiplying matrices - https://www.mathisfun.com/algebra/matrix-multiplying.html

ELement wise multiplication


In [57]:
tensor*tensor


tensor([100, 400, 900])

In [58]:
print(tensor,"*",tensor)
print(f"Equals : {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals : tensor([100, 400, 900])


In [59]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [60]:
## Matrix multiplication by hand

In [61]:
10*10+ 20*20+ 30*30

1400

In [62]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 2.2 ms, sys: 0 ns, total: 2.2 ms
Wall time: 4.39 ms


In [63]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 73 µs, sys: 11 µs, total: 84 µs
Wall time: 89.9 µs


tensor(1400)

There are two main rules that performing matrix multiplication needs to satisfy.

Inner dimensions must match
(3,2) @ (3,2) won't work
(2,3) @ (3,2) will work
(3,2) @ (2,3) will work

In [64]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[1.3381, 1.0421],
        [0.4026, 0.2945]])

The resulting matrix has the shape of the outer dmensions

In [65]:
x= (torch.rand(10,10) @ torch.rand(10,10))
x

tensor([[2.1419, 2.1760, 2.8335, 2.6808, 1.8448, 2.3507, 2.0932, 2.0600, 1.8267,
         2.2424],
        [2.3615, 2.2190, 3.0200, 2.1508, 1.4499, 2.1239, 1.6814, 1.9113, 1.7067,
         1.9952],
        [1.8692, 1.2772, 1.2598, 1.5838, 1.8954, 1.5385, 1.5701, 2.0959, 0.9633,
         1.5298],
        [1.8761, 1.6038, 1.8870, 1.6903, 1.7355, 1.6477, 1.5743, 1.9164, 1.0561,
         1.5220],
        [2.2591, 2.3337, 3.1942, 2.4138, 1.6382, 2.1376, 1.8529, 1.5482, 1.4426,
         2.3062],
        [1.5112, 1.7713, 2.4098, 2.0822, 1.1519, 1.8350, 1.2173, 1.2674, 1.2813,
         1.8327],
        [2.2454, 2.6885, 3.2279, 2.7262, 1.4446, 1.9196, 1.8874, 1.8519, 1.7826,
         2.3957],
        [2.5867, 2.4331, 3.6931, 2.8631, 1.9994, 2.8394, 2.3576, 2.1863, 2.2587,
         2.2598],
        [2.2436, 2.5661, 3.2491, 3.1749, 1.7272, 2.5003, 1.9673, 1.8453, 1.7232,
         3.0510],
        [2.3705, 2.0679, 3.4247, 2.8460, 1.4045, 2.3644, 1.9207, 1.2555, 1.7726,
         2.9079]])

In [66]:
print(x)

tensor([[2.1419, 2.1760, 2.8335, 2.6808, 1.8448, 2.3507, 2.0932, 2.0600, 1.8267,
         2.2424],
        [2.3615, 2.2190, 3.0200, 2.1508, 1.4499, 2.1239, 1.6814, 1.9113, 1.7067,
         1.9952],
        [1.8692, 1.2772, 1.2598, 1.5838, 1.8954, 1.5385, 1.5701, 2.0959, 0.9633,
         1.5298],
        [1.8761, 1.6038, 1.8870, 1.6903, 1.7355, 1.6477, 1.5743, 1.9164, 1.0561,
         1.5220],
        [2.2591, 2.3337, 3.1942, 2.4138, 1.6382, 2.1376, 1.8529, 1.5482, 1.4426,
         2.3062],
        [1.5112, 1.7713, 2.4098, 2.0822, 1.1519, 1.8350, 1.2173, 1.2674, 1.2813,
         1.8327],
        [2.2454, 2.6885, 3.2279, 2.7262, 1.4446, 1.9196, 1.8874, 1.8519, 1.7826,
         2.3957],
        [2.5867, 2.4331, 3.6931, 2.8631, 1.9994, 2.8394, 2.3576, 2.1863, 2.2587,
         2.2598],
        [2.2436, 2.5661, 3.2491, 3.1749, 1.7272, 2.5003, 1.9673, 1.8453, 1.7232,
         3.0510],
        [2.3705, 2.0679, 3.4247, 2.8460, 1.4045, 2.3644, 1.9207, 1.2555, 1.7726,
         2.9079]])


In [67]:
## Shapes for matrix multiplication

In [68]:
tensor_A = torch.tensor([[1,2,3],
                         [4,5,6]])


In [69]:
tensor_B = torch.tensor([[11,12,13],
                         [14,15,16]])


In [71]:
tensor_c = torch.matmul(tensor_A,tensor_B)
tensor_c

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [72]:
tensor_BB = tensor_B.T

In [73]:
tensor_C = torch.matmul(tensor_A, tensor_BB)

In [74]:
tensor_C

tensor([[ 74,  92],
        [182, 227]])

The matrix multiplication operation works when tensor_B is transposed

In [75]:
print(f"Original Shapes : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")

Original Shapes : tensor_A = torch.Size([2, 3]), tensor_B = torch.Size([2, 3])


In [76]:
print(f"New Shapes after the transpose is : {tensor_A.shape} )same shape as above, {tensor_BB.shape}")

New Shapes after the transpose is : torch.Size([2, 3]) )same shape as above, torch.Size([3, 2])


In [77]:
print(f"The Orginal shape of the tensors : {tensor_A.shape}, {tensor_B.shape}")
print(f"The New shape of the tensors : {tensor_A.shape} ( Here the shape is same as before , {tensor_BB.shape} (Here the shape is transposed)")
print(f"Multyplying : {tensor_A.shape} @ {tensor_BB.shape}")
print("output:\n")
output = torch.matmul(tensor_A,tensor_BB)
print(output)
print(f"\n Output shape : {output.shape}")

The Orginal shape of the tensors : torch.Size([2, 3]), torch.Size([2, 3])
The New shape of the tensors : torch.Size([2, 3]) ( Here the shape is same as before , torch.Size([3, 2]) (Here the shape is transposed)
Multyplying : torch.Size([2, 3]) @ torch.Size([3, 2])
output:

tensor([[ 74,  92],
        [182, 227]])

 Output shape : torch.Size([2, 2])


In [78]:
## Tensor Aggregation
## Find the min,max,mean,sum, etc (tensor aggregation)

In [79]:
# Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [80]:
# Find the min
torch.min(x)

tensor(1)

In [81]:
x.min()

tensor(1)

In [82]:
## Find the max
torch.max(x)

tensor(91)

In [83]:
x.max()

tensor(91)

In [84]:
# Find the mean
torch.mean(x,dtype = torch.float32)

tensor(46.)

In [85]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [86]:
torch.mean(...)

TypeError: mean(): argument 'input' (position 1) must be Tensor, not ellipsis

In [ ]:
## Find the Sum
torch.sum(x) , x.sum()

In [ ]:
torch.argmin(x)

In [ ]:
torch.argmax(x)

Arg min and Arg max are used to find the positional minimum and maximum.

Returns the index position of the target tensor

In [87]:
## Find the position in tensor that has the maximum value with argmax()

## Reshaping ,stacking,squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other ( Horizontal and Vertical are some of the many options)
* Squeeze - remove all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [88]:
## Let's create a tensor
import torch
x = torch.arange(1.,10.)
x.shape

torch.Size([9])

In [89]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [90]:
# Add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [91]:
# Change the view

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Changing z changes x (because a view of a tensor shares the same memory as the original tensor


In [92]:
z = torch.arange(1,10,2)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [93]:
z = x.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [94]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
## Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [96]:
x_stacked = torch.stack([x,
                         x,
                         x,
                         x], dim = 0)

In [97]:
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

Torch Squeeze and Unsqueeze

Torch Squeeze removes all single dimensions from a tensor.

In [98]:
x = torch.zeros(2,1,2,1,2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [99]:
y = torch.squeeze(x)
y


tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [100]:
y.size()

torch.Size([2, 2, 2])

In [101]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [102]:
print(f"Previous tensor : {x}")
print(f"Previous shape : {x.shape}")

# Remove extra dimensions from x
x_squeezed = x.squeeze()
print(f"\n New tensor : {x_squeezed}")

Previous tensor : tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
Previous shape : torch.Size([2, 1, 2, 1, 2])

 New tensor : tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


Unsqueezing adds an extra dimension to the tensor

In [103]:
print(f"Previous tensor : {x_squeezed}")
print(f"Previous Tensor Shape : {x_squeezed.shape}")

## Add an extra dimension to the Previous Tensor

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\n New Tensor : {x_unsqueezed}")
print(f"\n The Shape of the new tensor : {x_unsqueezed.shape}")


Previous tensor : tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
Previous Tensor Shape : torch.Size([2, 2, 2])

 New Tensor : tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])

 The Shape of the new tensor : torch.Size([1, 2, 2, 2])


Now let us try the tensor permutations where we change the order of dimensions or axis.

In [104]:
# Lets us first create a random image tensor

x = torch.rand(224,224,3)
x

tensor([[[0.3988, 0.1735, 0.3531],
         [0.0036, 0.6643, 0.6806],
         [0.1617, 0.7675, 0.1909],
         ...,
         [0.9859, 0.4562, 0.7221],
         [0.3256, 0.2412, 0.7397],
         [0.0667, 0.0562, 0.3342]],

        [[0.5779, 0.5488, 0.3087],
         [0.9154, 0.9149, 0.0600],
         [0.1758, 0.7027, 0.3371],
         ...,
         [0.7619, 0.2513, 0.1220],
         [0.0206, 0.2444, 0.9415],
         [0.9383, 0.6430, 0.0555]],

        [[0.1122, 0.7525, 0.8843],
         [0.4719, 0.9252, 0.5671],
         [0.4300, 0.1646, 0.2310],
         ...,
         [0.3567, 0.0585, 0.3653],
         [0.4843, 0.8688, 0.5261],
         [0.5419, 0.3894, 0.7089]],

        ...,

        [[0.5342, 0.4071, 0.0737],
         [0.4915, 0.0413, 0.3855],
         [0.5405, 0.5835, 0.2951],
         ...,
         [0.7274, 0.4863, 0.2840],
         [0.7075, 0.3511, 0.9657],
         [0.1156, 0.7904, 0.6901]],

        [[0.5354, 0.9866, 0.1724],
         [0.9633, 0.5640, 0.0582],
         [0.

In [105]:
print(f"The shape of the orginal tensor : {x.shape}")
print(f" \n When we permute the tensor , we get : {x.permute(2,0,1)}")
print(f"\n The shape of the original tensor is {x.shape} and the shape of the permuted tensor is \n {x.permute(2,0,1).shape}")

The shape of the orginal tensor : torch.Size([224, 224, 3])
 
 When we permute the tensor , we get : tensor([[[0.3988, 0.0036, 0.1617,  ..., 0.9859, 0.3256, 0.0667],
         [0.5779, 0.9154, 0.1758,  ..., 0.7619, 0.0206, 0.9383],
         [0.1122, 0.4719, 0.4300,  ..., 0.3567, 0.4843, 0.5419],
         ...,
         [0.5342, 0.4915, 0.5405,  ..., 0.7274, 0.7075, 0.1156],
         [0.5354, 0.9633, 0.6290,  ..., 0.3206, 0.7258, 0.0549],
         [0.5409, 0.4799, 0.2754,  ..., 0.3482, 0.7455, 0.1329]],

        [[0.1735, 0.6643, 0.7675,  ..., 0.4562, 0.2412, 0.0562],
         [0.5488, 0.9149, 0.7027,  ..., 0.2513, 0.2444, 0.6430],
         [0.7525, 0.9252, 0.1646,  ..., 0.0585, 0.8688, 0.3894],
         ...,
         [0.4071, 0.0413, 0.5835,  ..., 0.4863, 0.3511, 0.7904],
         [0.9866, 0.5640, 0.0553,  ..., 0.0442, 0.6342, 0.4345],
         [0.7348, 0.8400, 0.8866,  ..., 0.1263, 0.1957, 0.3185]],

        [[0.3531, 0.6806, 0.1909,  ..., 0.7221, 0.7397, 0.3342],
         [0.3087, 0.06

In [106]:
# torch.unsqueeze()- adds a single dimension to a target tensor at speicific dim (dimension)

In [107]:
x_original = x[0,0,0]

In [108]:
x_original

tensor(0.3988)

Indexing with pytorch is similar to indexing with Numpy

In [109]:
## Indexing (selecting data )


In [110]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)

In [111]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [112]:
## Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [113]:
x[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [ ]:
 x = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])


In [ ]:
x

In [ ]:
x[:,2,2]

In [ ]:
x[0,2,2]

In [ ]:
x[:,:,2]

In [ ]:
x[:,0,2]

## Pytorch tensors and numpy

Numpy is a popular scientific python library  and because of this , pytorch has functionality to interact with it

Data in Numpy , want in Pytorch tyensor -> torch.from_numpy(ndarray)
Pytorch tensor -> Numpy -> torch.Tensor.numpy()

In [ ]:
## Pytorch tensors and numpy

import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)



In [ ]:
tensor

In [114]:
# change the value of array , what will this do to 'tensor'?

In [115]:
2+2

4

In [116]:
2+5

7

A B C D  E F G H I J K L M N O P Q R S T U V W X Y Z

In [117]:
## tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

The data type of pytorch tensor is float64 and data type of numpy array is float 32. We have to be careful about this in future while converting pytorch tensor to numpy array and vice versa

In [118]:
numpy_tensor.dtype

dtype('float32')

Reproducibility : Trying to take out randomness out of random

In short how a neural network learns:

'start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again...

To reduce the randomness in neural networks and pytorch comes the concept of a * random seed *

What the random seed does is "flavour" the randomness

In [119]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5901, 0.3556, 0.0902, 0.1368],
        [0.5222, 0.8242, 0.4011, 0.8274],
        [0.6775, 0.4196, 0.2002, 0.3159]])
tensor([[0.4568, 0.3555, 0.8211, 0.9061],
        [0.8513, 0.7246, 0.9528, 0.7416],
        [0.2236, 0.7144, 0.4552, 0.6373]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [120]:
# Let's make some random but reproducible tensors
import torch
# Set the random_seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs ( and making faster computations)

GPUs = faster computation on numbers , thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything good

In [121]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [122]:
import torch
torch.cuda.is_available()

False

In [123]:
## Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [124]:
## count number of devices
torch.cuda.device_count()

0

In [125]:
tensor = torch.tensor([1,2,3])

In [126]:
tensor.device

device(type='cpu')

In [127]:
tensor_gpu = tensor.to(device)

In [128]:
tensor_gpu.device

device(type='cpu')

In [129]:
tensor.cpu()

tensor([1, 2, 3])

##